const createSecuritiesForm = [
  {
    label: "Security Name",
    name: "name",
    type: "text",
    required: true,
    span: 6,
    placeholder: "Security Name",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Name contains invalid characters",
    maxLength: 100,
    helperText: "Security Name is required",
  },
  {
    label: "Type",
    name: "type",
    type: "text",
    required: true,
    span: 6,
    placeholder: "Type",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Type contains invalid characters",
    maxLength: 50,
  },
  {
    label: "Description",
    name: "description",
    type: "textarea",
    required: false,
    span: 12,
    placeholder: "Description (optional)",
    rows: 2,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Description contains invalid characters",
    maxLength: 200,
  },
  {
    label: "Value",
    name: "value",
    type: "text",
    required: true,
    span: 6,
    placeholder: "Value",
    validationType: "string",
    validationPattern: /^\d+(\.\d{1,2})?$/,
    validationMessage: "Value must be a number",
    maxLength: 20,
  },
  {
    label: "Status",
    name: "status",
    type: "radio",
    required: false,
    span: 6,
    options: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
    ],
    showOnlyInEditMode: true,
  },
];

export default createSecuritiesForm;
