const createLoanProductForm = [
  {
    label: "Loan Product Name",
    name: "name",
    type: "text",
    required: true,
    span: 12,
    validationType: "string",
    validationMessage: "Loan Product Name is required",
    maxLength: 100,
  },
  {
    label: "Branches",
    name: "branch",
    type: "selectMultiple",
    span: 12,
    options: [], // Will be populated dynamically
    dynamicoptions: "true",
    required: true,
    placeholder: "Select Branches",
    helperText: "This loan product will only be available to the selected Branches.",
    showSelectAll: true
  },
  // Principal Settings
  {
    label: "Principal Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Minimum Principal",
    name: "minPrincipal",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  {
    label: "Default Principal",
    name: "defaultPrincipal",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  {
    label: "Maximum Principal",
    name: "maxPrincipal",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  // Interest Settings
  {
    label: "Interest Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Interest Method",
    name: "interestMethod",
    type: "select",
    span: 6,
    options: [
    { value: "flat", label: "Flat" },
    { value: "declining_balance", label: "Declining Balance" },
    { value: "reducing_balance_equal_installments", label: "Reducing Balance - Equal Installments" },
    { value: "reducing_balance_equal_principal", label: "Reducing Balance - Equal Principal" },
    { value: "interest_only", label: "Interest-Only" },
    { value: "compound_interest_accrued", label: "Compound Interest - Accrued" },
    { value: "compound_interest_equal_installments", label: "Compound Interest - Equal Installments" },
],
  },
  {
    label: "Interest Type",
    name: "interestType",
    type: "select",
    span: 6,
    options: [
      { value: "percentage", label: "Percentage" },
      { value: "fixed", label: "Fixed Amount" },
    ],
  },
  {
    label: "Interest Period",
    name: "interestPeriod",
    type: "select",
    span: 6,
    options: [
        { value: "per_day", label: "Per Day" },
        { value: "per_week", label: "Per Week" },
        { value: "per_month", label: "Per Month" },
        { value: "per_year", label: "Per Year" },
        { value: "per_loan_cycle", label: "Per Loan Cycle" },
    ],
  },
  {
    label: "Minimum Interest",
    name: "minInterest",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  {
    label: "Default Interest",
    name: "defaultInterest",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  {
    label: "Maximum Interest",
    name: "maxInterest",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  // Duration Settings
  {
    label: "Duration Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Duration Period",
    name: "durationPeriod",
    type: "select",
    span: 6,
    options: [
      { value: "days", label: "Days" },
      { value: "weeks", label: "Weeks" },
      { value: "months", label: "Months" },
      { value: "years", label: "Years" },
    ],
  },
  {
    label: "Minimum Duration",
    name: "minDuration",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  {
    label: "Default Duration",
    name: "defaultDuration",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  {
    label: "Maximum Duration",
    name: "maxDuration",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  // Repayment Settings
  {
    label: "Repayment Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Repayment Frequency",
    name: "repaymentFrequency",
    type: "select",
    span: 12,
    options: [
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
      { value: "biweekly", label: "Bi-weekly" },
      { value: "monthly", label: "Monthly" },
      { value: "bimonthly", label: "Bimonthly" },
      { value: "quarterly", label: "Quarterly" },
      { value: "every_4_months", label: "Every 4 months" },
      { value: "semi_annual", label: "Semi-annual" },
      { value: "every_9_months", label: "Every 9 months" },
      { value: "yearly", label: "Yearly" },
      { value: "lump_sum", label: "Lump Sum" },
    ],
  },
  {
    label: "Repayment Order",
    name: "repaymentOrder",
    type: "orderedList",
    span: 12,
    defaultValue: ["Penalty", "Fees", "Interest", "Principal"],
    helperText: "This is the order in which received payments are allocated. For example, if the order is Fees → Principal → Interest → Penalty and a $100 payment is received, the system first covers any Fees, then applies the remainder to Principal, then Interest, and finally Penalty.",
  },
  // Loan Maturity Settings
  {
    label: "Loan Maturity Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Should the Loan extend after Maturity?",
    name: "extendLoanAfterMaturity",
    type: "radio",
    span: 12,
    defaultValue: "no",
    options: [
      { value: "no", label: "No" },
      { value: "yes", label: "Yes" },
    ],
  },
  {
    label: "Interest Type after Maturity",
    name: "interestTypeMaturity",
    type: "radio",
    span: 12,
    defaultValue: "percentage",
    options: [
      { value: "percentage", label: "I want Interest to be percentage % based" },
      { value: "fixed", label: "I want Interest to be a fixed amount" },
    ],
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
  },
  {
    label: "Calculate Interest on",
    name: "calculateInterestOn",
    type: "select",
    span: 12,
    options: [
      { value: "Overdue Principal Amount", label: "Overdue Principal Amount" },
      { value: "Overdue Interest Amount", label: "Overdue Interest Amount" },
      { value: "Overdue (Principal + Interest) Amount", label: "Overdue (Principal + Interest) Amount" },
      { value: "Overdue (Principal + Interest + Fees) Amount", label: "Overdue (Principal + Interest + Fees) Amount" },
      { value: "Overdue (Principal + Interest + Penalty) Amount", label: "Overdue (Principal + Interest + Penalty) Amount" },
      { value: "Overdue (Principal + Interest + Fees + Penalty) Amount", label: "Overdue (Principal + Interest + Fees + Penalty) Amount" },
      { value: "Overdue (Interest + Fees) Amount", label: "Overdue (Interest + Fees) Amount" },
      { value: "Total Principal Amount Released", label: "Total Principal Amount Released" },
      { value: "Total Principal Balance Amount", label: "Total Principal Balance Amount" },
      { value: "Maturity Date Installment Only - Overdue Principal Amount", label: "Maturity Date Installment Only - Overdue Principal Amount" },
      { value: "Maturity Date Installment Only - Overdue Interest Amount", label: "Maturity Date Installment Only - Overdue Interest Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest + Penalty) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest + Penalty) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees + Penalty) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees + Penalty) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Interest + Fees) Amount", label: "Maturity Date Installment Only - Overdue (Interest + Fees) Amount" },
    ],
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
    dynamicLabel: true, // Label changes based on interestTypeMaturity
  },
  {
    label: "Interest Rate After Maturity",
    name: "loanInterestRateAfterMaturity",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
    dynamicLabel: true, // Label changes based on interestTypeMaturity
  },
  {
    label: "Interest Period After Maturity",
    name: "recurringPeriodAfterMaturityUnit",
    type: "select",
    span: 6,
    options: [
      { value: "Daily", label: "Daily" },
      { value: "Weekly", label: "Weekly" },
      { value: "Every 2 weeks", label: "Every 2 weeks" },
      { value: "Monthly", label: "Monthly" },
      { value: "Every 2 Months", label: "Every 2 Months" },
      { value: "Every 3 Months", label: "Every 3 Months" },
      { value: "Every 4 Months", label: "Every 4 Months" },
      { value: "Every 6 Months", label: "Every 6 Months" },
      { value: "Every 9 Months", label: "Every 9 Months" },
      { value: "Yearly", label: "Yearly" },
      { value: "One-off / Lump-Sum", label: "One-off / Lump-Sum" },
    ],
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
  },
  {
    label: "Fees & Charges",
    type: "label",
    span: 12,
  },
  {
    label: "Loan Fees",
    name: "loanFees",
    type: "selectMultiple",
    span: 12,
    multiple: true,
    options: [], // Will be populated dynamically
    dynamicoptions: "true",
  },
];

export default createLoanProductForm;
