import { Settings } from "@mui/icons-material";

const createLoanForm = [
  {
    label: "Loan Product",
    name: "loanProduct",
    type: "select",
    span: 12,
    options: [], // Will be populated dynamically
    dynamicoptions: "true",
    helperText: "Use a pre-set Loan Product."
  },

  // Principal Settings
  {
    label: "Principal Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Principal Amount",
    name: "principalAmount",
    type: "number",
    required: true,
    span: 12,
    validationType: "number",
    min: 0,
    helperText: "The amount of money being lent."
  },

  // Interest Settings
  {
    label: "Interest Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Interest Method",
    name: "interestMethod",
    type: "select",
    span: 12,
    required: true,
    defaultValue: "reducing_balance_equal_installments",
    options: [
      { value: "compound_interest_accrued", label: "Compound Interest - Accrued" },
      { value: "compound_interest_equal_installments", label: "Compound Interest - Equal Installments" },
      { value: "flat", label: "Flat" },
      { value: "interest_only", label: "Interest-Only" },
      { value: "reducing_balance_equal_installments", label: "Reducing Balance - Equal Installments" },
      { value: "reducing_balance_equal_principal", label: "Reducing Balance - Equal Principal" },
    ],
    dynamicHelperText: {
      compound_interest_accrued: "Any unpaid interest is added to the loan balance. Future interest is then calculated on this new, higher balance (interest on interest).",
      compound_interest_equal_installments: "Interest compounds (accumulates on the balance), but the borrower makes fixed payments to pay it down over time.",
      flat: "Interest is based on the original loan amount (principal) and stays the same throughout the loan. Interest does not change even as the borrower pays it off.",
      interest_only: "The borrower only pays the interest charges for a set period. The borrowed amount (principal) is not paid back until later.",
      reducing_balance_equal_installments: "The borrower's payment amount is the same each time (Amortized). Early payments cover mostly interest, while later payments pay off the principal.",
      reducing_balance_equal_principal: "The borrower pays a fixed amount of principal plus the interest due. This makes the total payment decrease over time.",
    },
  },
  {
    label: "Interest Type",
    name: "interestType",
    type: "radio",
    span: 6,
    required: true,
    defaultValue: "percentage",
    options: [
      { value: "percentage", label: "Percentage" },
      { value: "fixed", label: "Fixed Amount" },
    ],
  },
  {
    type: "textAndDropdown",
    span: 6,
    textLabel: "Interest Rate",
    textName: "interestRate",
    textType: "number",
    textRequired: true,
    textDefaultValue: "",
    textPlaceholder: "",
    textHelperText: "",
    textInputProps: {
      validationType: "number",
      min: 0,
    },
    dynamicLabel: true,
    dynamicLabelMap: {
      percentage: "Interest Rate",
      fixed: "Interest Amount",
    },
    dependsOn: "interestType",
    dropdownLabel: "",
    dropdownName: "interestPeriod",
    dropdownRequired: true,
    dropdownDefaultValue: "per_month",
    dropdownHelperText: "",
    dropdownOptions: [
      { value: "per_day", label: "Per Day" },
      { value: "per_week", label: "Per Week" },
      { value: "per_month", label: "Per Month" },
      { value: "per_year", label: "Per Year" },
      { value: "per_loan", label: "Per Loan" },
    ],
  },

  // Duration Settings
  {
    label: "Duration Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Loan Start Date",
    name: "loanStartDate",
    type: "date",
    required: true,
    span: 6,
  },
  {
    type: "textAndDropdown",
    span: 6,
    textLabel: "Loan Duration",
    textName: "loanDuration",
    textType: "number",
    textRequired: true,
    textDefaultValue: "",
    textPlaceholder: "",
    textHelperText: "",
    textInputProps: {
      validationType: "number",
      min: 1,
    },
    dropdownLabel: "",
    dropdownName: "durationPeriod",
    dropdownRequired: true,
    dropdownDefaultValue: "months",
    dropdownHelperText: "",
    dropdownOptions: [
      { value: "days", label: "Days" },
      { value: "weeks", label: "Weeks" },
      { value: "months", label: "Months" },
      { value: "years", label: "Years" },
    ],
  },
  

  // Repayment Settings
  {
    label: "Repayment Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Repayment Frequency",
    name: "repaymentFrequencyType",
    type: "radio",
    required: true,
    span: 12,
    defaultValue: "interval",
    options: [
      { value: "interval", label: "Interval Based" },
      { value: "lumpSum", label: "Lump Sum" },
      { value: "setDays", label: "Set Days of the Week" },
      { value: "setDates", label: "Set Dates of the Month" },
    ],
    helperText: "Choose how repayments will be scheduled."
  },
  {
    label: "Repayment Interval",
    name: "repaymentFrequency",
    type: "select",
    span: 6,
    defaultValue: "monthly",
    options: [
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
      { value: "biweekly", label: "Every 2 weeks" },
      { value: "monthly", label: "Monthly" },
      { value: "quarterly", label: "Quarterly" },
      { value: "every_4_months", label: "Every 4 months" },
      { value: "semi_annual", label: "Semi-annual" },
      { value: "every_9_months", label: "Every 9 months" },
      { value: "yearly", label: "Yearly" },
    ],
    helperText: "Select the interval for repayment.",
    dependsOn: "repaymentFrequencyType",
    dependsOnValue: "interval",
  },
  {
    label: "Payment Days",
    name: "customPaymentDays",
    type: "selectMultiple",
    span: 6,
    options: [
      { value: "Monday", label: "Monday" },
      { value: "Tuesday", label: "Tuesday" },
      { value: "Wednesday", label: "Wednesday" },
      { value: "Thursday", label: "Thursday" },
      { value: "Friday", label: "Friday" },
      { value: "Saturday", label: "Saturday" },
      { value: "Sunday", label: "Sunday" },
    ],
    helperText: "Select the days of the week on which payments should be received.",
    dependsOn: "repaymentFrequencyType",
    dependsOnValue: "setDays",
    showSelectAll: false,
  },
  {
    label: "Payment Dates",
    name: "customPaymentDates",
    type: "selectMultiple",
    span: 6,
    options: [
      { value: "1", label: "1st" },
      { value: "2", label: "2nd" },
      { value: "3", label: "3rd" },
      { value: "4", label: "4th" },
      { value: "5", label: "5th" },
      { value: "6", label: "6th" },
      { value: "7", label: "7th" },
      { value: "8", label: "8th" },
      { value: "9", label: "9th" },
      { value: "10", label: "10th" },
      { value: "11", label: "11th" },
      { value: "12", label: "12th" },
      { value: "13", label: "13th" },
      { value: "14", label: "14th" },
      { value: "15", label: "15th" },
      { value: "16", label: "16th" },
      { value: "17", label: "17th" },
      { value: "18", label: "18th" },
      { value: "19", label: "19th" },
      { value: "20", label: "20th" },
      { value: "21", label: "21st" },
      { value: "22", label: "22nd" },
      { value: "23", label: "23rd" },
      { value: "24", label: "24th" },
      { value: "25", label: "25th" },
      { value: "26", label: "26th" },
      { value: "27", label: "27th" },
      { value: "28", label: "28th" },
      { value: "29", label: "29th" },
      { value: "30", label: "30th" },
      { value: "31", label: "31st" },
    ],
    helperText: "Select the dates of the month on which payments should be received.",
    dependsOn: "repaymentFrequencyType",
    dependsOnValue: "setDates",
    showSelectAll: false,
  },
  
  // Loan Maturity Settings
  {
    label: "Loan Maturity Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Should the Loan extend after Maturity?",
    name: "extendLoanAfterMaturity",
    type: "radio",
    span: 12,
    defaultValue: "no",
    options: [
      { value: "no", label: "No" },
      { value: "yes", label: "Yes" },
    ],
  },
  {
    label: "Interest Type after Maturity",
    name: "interestTypeMaturity",
    type: "radio",
    span: 12,
    defaultValue: "percentage",
    options: [
      { value: "percentage", label: "I want Interest to be percentage % based" },
      { value: "fixed", label: "I want Interest to be a fixed amount" },
    ],
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
  },
  {
    label: "Calculate Interest on",
    name: "calculateInterestOn",
    type: "select",
    span: 12,
    options: [
      { value: "Overdue Principal Amount", label: "Overdue Principal Amount" },
      { value: "Overdue Interest Amount", label: "Overdue Interest Amount" },
      { value: "Overdue (Principal + Interest) Amount", label: "Overdue (Principal + Interest) Amount" },
      { value: "Overdue (Principal + Interest + Fees) Amount", label: "Overdue (Principal + Interest + Fees) Amount" },
      { value: "Overdue (Principal + Interest + Penalty) Amount", label: "Overdue (Principal + Interest + Penalty) Amount" },
      { value: "Overdue (Principal + Interest + Fees + Penalty) Amount", label: "Overdue (Principal + Interest + Fees + Penalty) Amount" },
      { value: "Overdue (Interest + Fees) Amount", label: "Overdue (Interest + Fees) Amount" },
      { value: "Total Principal Amount Released", label: "Total Principal Amount Released" },
      { value: "Total Principal Balance Amount", label: "Total Principal Balance Amount" },
      { value: "Maturity Date Installment Only - Overdue Principal Amount", label: "Maturity Date Installment Only - Overdue Principal Amount" },
      { value: "Maturity Date Installment Only - Overdue Interest Amount", label: "Maturity Date Installment Only - Overdue Interest Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest + Penalty) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest + Penalty) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees + Penalty) Amount", label: "Maturity Date Installment Only - Overdue (Principal + Interest + Fees + Penalty) Amount" },
      { value: "Maturity Date Installment Only - Overdue (Interest + Fees) Amount", label: "Maturity Date Installment Only - Overdue (Interest + Fees) Amount" },
    ],
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
    dynamicLabel: true,
  },
  {
    label: "Interest Rate After Maturity",
    name: "loanInterestRateAfterMaturity",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
    dynamicLabel: true,
  },
  {
    label: "Interest Period After Maturity",
    name: "recurringPeriodAfterMaturityUnit",
    type: "select",
    span: 6,
    options: [
      { value: "Daily", label: "Daily" },
      { value: "Weekly", label: "Weekly" },
      { value: "Every 2 weeks", label: "Every 2 weeks" },
      { value: "Monthly", label: "Monthly" },
      { value: "Every 2 Months", label: "Every 2 Months" },
      { value: "Every 3 Months", label: "Every 3 Months" },
      { value: "Every 4 Months", label: "Every 4 Months" },
      { value: "Every 6 Months", label: "Every 6 Months" },
      { value: "Every 9 Months", label: "Every 9 Months" },
      { value: "Yearly", label: "Yearly" },
      { value: "One-off / Lump-Sum", label: "One-off / Lump-Sum" },
    ],
    dependsOn: "extendLoanAfterMaturity",
    dependsOnValue: "yes",
  },

  // Fees & Charges
  {
    label: "Loan Fees",
    type: "label",
    span: 12,
  },
  {
    label: "Loan Fees Configuration",
    name: "loanFeesType",
    type: "radio",
    span: 12,
    defaultValue: "none",
    options: [
      { value: "none", label: "No Loan Fees" },
      { value: "pre-defined", label: "Use Pre-defined Loan Fees" },
      { value: "custom", label: "Enter Custom Amount" },
    ],
    helperText: "Choose whether to use a predefined loan fees model or enter a custom fee amount.",
  },
  {
    label: "Pre-defined Loan Fees",
    name: "loanFees",
    type: "select",
    span: 6,
    options: [], // Will be populated dynamically
    dynamicoptions: "true",
    dependsOn: "loanFeesType",
    dependsOnValue: "pre-defined",
    helperText: "Select a predefined loan fee.",
  },
  {
    label: "Custom Loan Fee Amount",
    name: "customLoanFeeAmount",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
    dependsOn: "loanFeesType",
    dependsOnValue: "custom",
    helperText: "Enter the custom fee amount.",
  },
  {
    label: "Loan Fees",
    type: "formLink",
    span: 12,
    linkText: "Configure Loan Fees",
    linkUrl: "/admin/loan-fees",
    icon: Settings,
    dependsOn: "loanFeesType",
    dependsOnValue: ["pre-defined"],
  },

];

export default createLoanForm;