/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, TextAreaFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type BorrowerCreateFormInputValues = {
    firstname?: string;
    othername?: string;
    businessName?: string;
    typeOfBusiness?: string;
    uniqueIdNumber?: string;
    phoneNumber?: string;
    otherPhoneNumber?: string;
    email?: string;
    gender?: string;
    dateOfBirth?: string;
    nationality?: string;
    nationalIdPicture?: string;
    passportPicture?: string;
    address?: string;
    points?: number;
    borrowerOpeningBalance?: number;
    borrowerClosingBalance?: number;
    borrowerInterestRate?: number;
    city?: string;
    state?: string;
    title?: string;
    zipcode?: string;
    employmentStatus?: string;
    employerName?: string;
    creditScore?: string;
    additionalNote1?: string;
    additionalNote2?: string;
    borrowerDocument1?: string;
    borrowerDocument1URL?: string;
    borrowerDocument2?: string;
    borrowerDocument2URL?: string;
    borrowerDocument3?: string;
    borrowerDocument3URL?: string;
    borrowerDocument4?: string;
    borrowerDocument4URL?: string;
    borrowerStatus?: string;
    borrowertype?: string;
    borrowerAttribute1?: string;
    borrowerAttribute2?: string;
    customFieldsData?: string;
};
export declare type BorrowerCreateFormValidationValues = {
    firstname?: ValidationFunction<string>;
    othername?: ValidationFunction<string>;
    businessName?: ValidationFunction<string>;
    typeOfBusiness?: ValidationFunction<string>;
    uniqueIdNumber?: ValidationFunction<string>;
    phoneNumber?: ValidationFunction<string>;
    otherPhoneNumber?: ValidationFunction<string>;
    email?: ValidationFunction<string>;
    gender?: ValidationFunction<string>;
    dateOfBirth?: ValidationFunction<string>;
    nationality?: ValidationFunction<string>;
    nationalIdPicture?: ValidationFunction<string>;
    passportPicture?: ValidationFunction<string>;
    address?: ValidationFunction<string>;
    points?: ValidationFunction<number>;
    borrowerOpeningBalance?: ValidationFunction<number>;
    borrowerClosingBalance?: ValidationFunction<number>;
    borrowerInterestRate?: ValidationFunction<number>;
    city?: ValidationFunction<string>;
    state?: ValidationFunction<string>;
    title?: ValidationFunction<string>;
    zipcode?: ValidationFunction<string>;
    employmentStatus?: ValidationFunction<string>;
    employerName?: ValidationFunction<string>;
    creditScore?: ValidationFunction<string>;
    additionalNote1?: ValidationFunction<string>;
    additionalNote2?: ValidationFunction<string>;
    borrowerDocument1?: ValidationFunction<string>;
    borrowerDocument1URL?: ValidationFunction<string>;
    borrowerDocument2?: ValidationFunction<string>;
    borrowerDocument2URL?: ValidationFunction<string>;
    borrowerDocument3?: ValidationFunction<string>;
    borrowerDocument3URL?: ValidationFunction<string>;
    borrowerDocument4?: ValidationFunction<string>;
    borrowerDocument4URL?: ValidationFunction<string>;
    borrowerStatus?: ValidationFunction<string>;
    borrowertype?: ValidationFunction<string>;
    borrowerAttribute1?: ValidationFunction<string>;
    borrowerAttribute2?: ValidationFunction<string>;
    customFieldsData?: ValidationFunction<string>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type BorrowerCreateFormOverridesProps = {
    BorrowerCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    firstname?: PrimitiveOverrideProps<TextFieldProps>;
    othername?: PrimitiveOverrideProps<TextFieldProps>;
    businessName?: PrimitiveOverrideProps<TextFieldProps>;
    typeOfBusiness?: PrimitiveOverrideProps<TextFieldProps>;
    uniqueIdNumber?: PrimitiveOverrideProps<TextFieldProps>;
    phoneNumber?: PrimitiveOverrideProps<TextFieldProps>;
    otherPhoneNumber?: PrimitiveOverrideProps<TextFieldProps>;
    email?: PrimitiveOverrideProps<TextFieldProps>;
    gender?: PrimitiveOverrideProps<TextFieldProps>;
    dateOfBirth?: PrimitiveOverrideProps<TextFieldProps>;
    nationality?: PrimitiveOverrideProps<TextFieldProps>;
    nationalIdPicture?: PrimitiveOverrideProps<TextFieldProps>;
    passportPicture?: PrimitiveOverrideProps<TextFieldProps>;
    address?: PrimitiveOverrideProps<TextFieldProps>;
    points?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerOpeningBalance?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerClosingBalance?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerInterestRate?: PrimitiveOverrideProps<TextFieldProps>;
    city?: PrimitiveOverrideProps<TextFieldProps>;
    state?: PrimitiveOverrideProps<TextFieldProps>;
    title?: PrimitiveOverrideProps<TextFieldProps>;
    zipcode?: PrimitiveOverrideProps<TextFieldProps>;
    employmentStatus?: PrimitiveOverrideProps<TextFieldProps>;
    employerName?: PrimitiveOverrideProps<TextFieldProps>;
    creditScore?: PrimitiveOverrideProps<TextFieldProps>;
    additionalNote1?: PrimitiveOverrideProps<TextFieldProps>;
    additionalNote2?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument1?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument1URL?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument2?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument2URL?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument3?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument3URL?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument4?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerDocument4URL?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerStatus?: PrimitiveOverrideProps<TextFieldProps>;
    borrowertype?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerAttribute1?: PrimitiveOverrideProps<TextFieldProps>;
    borrowerAttribute2?: PrimitiveOverrideProps<TextFieldProps>;
    customFieldsData?: PrimitiveOverrideProps<TextAreaFieldProps>;
} & EscapeHatchProps;
export declare type BorrowerCreateFormProps = React.PropsWithChildren<{
    overrides?: BorrowerCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: BorrowerCreateFormInputValues) => BorrowerCreateFormInputValues;
    onSuccess?: (fields: BorrowerCreateFormInputValues) => void;
    onError?: (fields: BorrowerCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: BorrowerCreateFormInputValues) => BorrowerCreateFormInputValues;
    onValidate?: BorrowerCreateFormValidationValues;
} & React.CSSProperties>;
export default function BorrowerCreateForm(props: BorrowerCreateFormProps): React.ReactElement;
