import { countries } from "../../../Resources/listOfCountries";

const createBorrowerForm = [
  {
    label: "First Name:",
    name: "firstname",
    type: "text",
    required: false, // Custom validation handles this
    span: 6,
    helperText: "Either First Name or Business Name is required",
    autoComplete: "given-name",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Middle / Last Name:",
    name: "othername",
    type: "text",
    required: false,
    span: 6,
    autoComplete: "family-name",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Business Name:",
    name: "businessName",
    type: "text",
    required: false, // Custom validation handles this
    span: 12,
    autoComplete: "organization",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Unique Identification Number:",
    name: "uniqueNumber",
    type: "text",
    required: false,
    span: 12,
    helperText: "Enter a unique identifier for the borrower (e.g National ID, Social Security ID, License No., Registration No.)",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Mobile Number:",
    name: "mobile",
    type: "tel",
    required: false,
    span: 6,
    placeholder: "numbers only",    
    inputProps: { inputMode: "numeric", pattern: "[0-9]*" },
    helperText: "Do not put country code, spaces, or characters in the mobile field otherwise you won't be able to send SMS to the mobile.",
    validationType: "string",
    validationPattern: /^[0-9]*$/,
    validationMessage: "Mobile must contain numbers only",
    minLength: 7, // added minimum length
    maxLength: 20,
  },
  {
    label: "Alternative Phone Number:",
    name: "altPhone",
    type: "tel",
    required: false,
    span: 6,
    placeholder: "numbers only",    
    inputProps: { inputMode: "numeric", pattern: "[0-9]*" },
    validationType: "string",
    validationPattern: /^[0-9]*$/,
    validationMessage: "Alternative Phone must contain numbers only",
    minLength: 7, // added minimum length
    maxLength: 20,
  },
  {
    label: "Email:",
    name: "email",
    type: "email",
    required: false,
    span: 6,
    autoComplete: "email",
    validationType: "email",
    validationMessage: "Invalid email address",
  },
  {
    label: "Gender:",
    name: "gender",
    type: "select",
    required: false,
    span: 6,
    options: [
      { value: "Male", label: "Male" },
      { value: "Female", label: "Female" },
      { value: "Decline to State", label: "Decline to State" },
    ],
  },
  {
    label: "Title:",
    name: "title",
    type: "select",
    required: false,
    span: 6,
    options: [
      { value: "Mr.", label: "Mr." },
      { value: "Mrs.", label: "Mrs." },
      { value: "Ms.", label: "Ms." },
      { value: "Miss", label: "Miss" },
      { value: "Dr.", label: "Dr." },
      { value: "Prof.", label: "Prof." },
      { value: "Rev.", label: "Rev." },
      { value: "Hon.", label: "Hon." },
      { value: "Eng.", label: "Eng." },
    ],
  },
  {
    label: "Country:",
    name: "country",
    type: "select",
    required: false,
    span: 6,
    options: countries.map(c => ({ value: c, label: c })),
  },
  {
    label: "Address:",
    name: "address",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "City:",
    name: "city",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Province / State:",
    name: "province",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Zipcode:",
    name: "zipcode",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Date of Birth:",
    name: "dob",
    type: "date",
    required: false,
    span: 6,
    validationType: "date",
  },
  {
    label: "Working Status:",
    name: "workingStatus",
    type: "select",
    required: false,
    span: 6,
    options: [
      { value: "Employed", label: "Employed" },
      { value: "Self-Employed", label: "Self-Employed" },
      { value: "Unemployed", label: "Unemployed" },
      { value: "Student", label: "Student" },
      { value: "Retired", label: "Retired" },
      { value: "Homemaker", label: "Homemaker" },
      { value: "Part-time", label: "Part-time" },
      { value: "Contract", label: "Contract" },
      { value: "Other", label: "Other" },
    ],
  },
  {
    label: "Employer Name:",
    name: "employerName",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Credit Score:",
    name: "creditScore",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 1:",
    name: "placeholderField1",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 2:",
    name: "placeholderField2",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 3:",
    name: "placeholderField3",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 4:",
    name: "placeholderField4",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 5:",
    name: "placeholderField5",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 6:",
    name: "placeholderField6",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 7:",
    name: "placeholderField7",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 8:",
    name: "placeholderField8",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 9:",
    name: "placeholderField9",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 10:",
    name: "placeholderField10",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 11:",
    name: "placeholderField11",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 12:",
    name: "placeholderField12",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 13:",
    name: "placeholderField13",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 14:",
    name: "placeholderField14",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 15:",
    name: "placeholderField15",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 16:",
    name: "placeholderField16",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 17:",
    name: "placeholderField17",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 18:",
    name: "placeholderField18",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 19:",
    name: "placeholderField19",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 20:",
    name: "placeholderField20",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 21:",
    name: "placeholderField21",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 22:",
    name: "placeholderField22",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 23:",
    name: "placeholderField23",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 24:",
    name: "placeholderField24",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 25:",
    name: "placeholderField25",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 26:",
    name: "placeholderField26",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 27:",
    name: "placeholderField27",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 28:",
    name: "placeholderField28",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 29:",
    name: "placeholderField29",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 30:",
    name: "placeholderField30",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 31:",
    name: "placeholderField31",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 32:",
    name: "placeholderField32",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 33:",
    name: "placeholderField33",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 34:",
    name: "placeholderField34",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 35:",
    name: "placeholderField35",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 36:",
    name: "placeholderField36",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 37:",
    name: "placeholderField37",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 38:",
    name: "placeholderField38",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 39:",
    name: "placeholderField39",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 40:",
    name: "placeholderField40",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 41:",
    name: "placeholderField41",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 42:",
    name: "placeholderField42",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 43:",
    name: "placeholderField43",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 44:",
    name: "placeholderField44",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 45:",
    name: "placeholderField45",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 46:",
    name: "placeholderField46",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 47:",
    name: "placeholderField47",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 48:",
    name: "placeholderField48",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 49:",
    name: "placeholderField49",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 50:",
    name: "placeholderField50",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 51:",
    name: "placeholderField51",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 52:",
    name: "placeholderField52",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 53:",
    name: "placeholderField53",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 54:",
    name: "placeholderField54",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 55:",
    name: "placeholderField55",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 56:",
    name: "placeholderField56",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 57:",
    name: "placeholderField57",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 58:",
    name: "placeholderField58",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 59:",
    name: "placeholderField59",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Placeholder Field 60:",
    name: "placeholderField60",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
];

export default createBorrowerForm;
