const employeeForm = [
  {
    label: "Branch",
    name: "branchEmployeesId",
    type: "select",
    required: false,
    span: 12,
    options: [],
    adminOnly: true,
  },
  {
    label: "First Name",
    name: "firstName",
    type: "text",
    required: true,
    span: 6,
  },
  {
    label: "Last Name",
    name: "lastName",
    type: "text",
    required: true,
    span: 6,
  },
  {
    label: "Middle Name",
    name: "middleName",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    required: false,
    span: 6,
  },
  {
    label: "Phone Number",
    name: "phoneNumber1",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Title",
    name: "title",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Employment Position",
    name: "employmentPosition",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Department",
    name: "employmentDepartment",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Employment Type",
    name: "employmentType",
    type: "select",
    required: false,
    span: 6,
    options: [
      { value: "Full Time", label: "Full Time" },
      { value: "Part Time", label: "Part Time" },
      { value: "Contract", label: "Contract" },
      { value: "Temporary", label: "Temporary" },
      { value: "Consultant", label: "Consultant" },
    ],
  },
  {
    label: "Employment Status",
    name: "employmentStatus",
    type: "select",
    required: false,
    span: 6,
    options: [
      { value: "active", label: "Active" },
      { value: "on_leave", label: "On Leave" },
      { value: "suspended", label: "Suspended" },
      { value: "inactive", label: "Inactive" },
    ],
  },
  {
    label: "Date of Birth",
    name: "dateOfBirth",
    type: "date",
    required: false,
    span: 6,
  },
  {
    label: "Start Date",
    name: "employmentStartDate",
    type: "date",
    required: false,
    span: 6,
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    required: false,
    span: 6,
    onlyVisibleInEdit: true,
    options: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
      { value: "archived", label: "Archived" },
    ],
  },
  {
    label: "Address",
    name: "addressLine1",
    type: "text",
    required: false,
    span: 12,
  },
  {
    label: "City",
    name: "city",
    type: "text",
    required: false,
    span: 4,
  },
  {
    label: "State / Province",
    name: "stateProvince",
    type: "text",
    required: false,
    span: 4,
  },
  {
    label: "Postal Code",
    name: "postalCode",
    type: "text",
    required: false,
    span: 4,
  },
];

export default employeeForm;