const employeeForm = [
  {
    label: "Identification Details",
    type: "label",
    span: 12,
  },
  {
    label: "Branch",
    name: "branchEmployeesId",
    type: "select",
    required: false,
    span: 12,
    options: [],
    adminOnly: true,
  },
  {
    label: "First Name",
    name: "firstName",
    type: "text",
    required: true,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: 'Invalid characters found. Cannot use , " \' ! { }',
  },
  {
    label: "Last Name",
    name: "lastName",
    type: "text",
    required: true,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: 'Invalid characters found. Cannot use , " \' ! { }',
  },
  {
    label: "Middle Name",
    name: "middleName",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: 'Invalid characters found. Cannot use , " \' ! { }',
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    required: false,
    span: 6,
    validationType: "email",
    validationMessage: "Invalid email address",
  },
  {
    label: "Phone Number",
    name: "phoneNumber1",
    type: "tel",
    required: false,
    span: 6,
    placeholder: "numbers only",
    inputProps: { inputMode: "numeric", pattern: "[0-9]*" },
    validationType: "string",
    validationPattern: /^[0-9]*$/,
    validationMessage: "Phone must contain numbers only",
    minLength: 7,
    maxLength: 20,
  },
  {
    label: "Title",
    name: "title",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Unique Identification Number:",
    name: "nationalID", // updated
    type: "text",
    required: false,
    span: 12,
    helperText: "Enter a unique identifier for the employee (e.g National ID, Passport No.)",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Invalid characters found. Cannot use , \" ' ! { }",
  },
  {
    label: "Employment Information",
    type: "label",
    span: 12,
  },
  {
    label: "Employment Position",
    name: "employmentPosition",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Department",
    name: "employmentDepartment",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Employment Type",
    name: "employmentType",
    type: "select",
    required: false,
    span: 6,
    options: [
      { value: "Full Time", label: "Full Time" },
      { value: "Part Time", label: "Part Time" },
      { value: "Contract", label: "Contract" },
      { value: "Temporary", label: "Temporary" },
      { value: "Consultant", label: "Consultant" },
    ],
  },
  {
    label: "Employment Status",
    name: "employmentStatus",
    type: "select",
    required: false,
    span: 6,
    options: [
      { value: "active", label: "Active" },
      { value: "on_leave", label: "On Leave" },
      { value: "suspended", label: "Suspended" },
      { value: "inactive", label: "Inactive" },
    ],
  },
  {
    label: "Date of Birth",
    name: "dateOfBirth",
    type: "date",
    required: false,
    span: 6,
  },
  {
    label: "Start Date",
    name: "employmentStartDate",
    type: "date",
    required: false,
    span: 6,
  },
  {
    label: "Gross Salary",
    name: "grossSalary",
    type: "number",
    required: false,
    span: 6,
    validationType: "number",
  },
  {
    label: "Address Information",
    type: "label",
    span: 12,
  },
  {
    label: "Address",
    name: "addressLine1",
    type: "text",
    required: false,
    span: 12,
  },
  {
    label: "City",
    name: "city",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "State / Province",
    name: "stateProvince",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Postal Code",
    name: "postalCode",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Banking Information",
    type: "label",
    span: 12,
  },
  {
    label: "Bank Name",
    name: "bankName",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Bank Account Number",
    name: "bankAccountNumber",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Tax & Compliance",
    type: "label",
    span: 12,
  },
  {
    label: "Social Security Number",
    name: "socialSecurityNumber",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Tax Identification Number",
    name: "taxIdentificationNumber",
    type: "text",
    required: false,
    span: 6,
  },
  {
    label: "Next of Kin",
    type: "label",
    span: 12,
  },
  {
    label: "Next of Kin Name",
    name: "nextOfKinName",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: 'Invalid characters found. Cannot use , " \' ! { }',
  },
  {
    label: "Relationship",
    name: "nextOfKinRelationship",
    type: "text",
    required: false,
    span: 6,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: 'Invalid characters found. Cannot use , " \' ! { }',
  },
  {
    label: "Next of Kin Phone",
    name: "nextOfKinPhoneNumber",
    type: "tel",
    required: false,
    span: 6,
    placeholder: "numbers only",
    inputProps: { inputMode: "numeric", pattern: "[0-9]*" },
    validationType: "string",
    validationPattern: /^[0-9]*$/,
    validationMessage: "Phone must contain numbers only",
    minLength: 7,
    maxLength: 20,
  },
  {
    label: "Next of Kin Email",
    name: "nextOfKinEmail",
    type: "email",
    required: false,
    span: 6,
    validationType: "email",
    validationMessage: "Invalid email address",
  },
  {
    label: "Next of Kin Address",
    name: "nextOfKinAddress",
    type: "text",
    required: false,
    span: 12,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: 'Invalid characters found. Cannot use , " \' ! { }',
  },
    {
    label: "Status in System",
    type: "label",
    span: 12,
  },
  {
    label: "Status in System",
    name: "status",
    type: "select",
    required: false,
    span: 6,
    onlyVisibleInEdit: true,
    options: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
      { value: "archived", label: "Archived" },
    ],
  },

];

export default employeeForm;