export const accountInfoForm = [
  {
    label: "User Details",
    type: "label",
    span: 12,
  },
  {
    label: "Email",
    name: "email",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "User Type",
    name: "userType",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "First Name",
    name: "firstName",
    type: "text",
    span: 6,
  },
  {
    label: "Last Name",
    name: "lastName",
    type: "text",
    span: 6,
  },
  {
    label: "Phone Number",
    name: "phoneNumber1",
    type: "text",
    span: 6,
  },
  {
    label: "Date of Birth",
    name: "dateOfBirth",
    type: "date",
    span: 6,
  },
  {
    label: "National ID",
    name: "nationalID",
    type: "text",
    span: 6,
  },
  {
    label: "System Information",
    type: "label",
    span: 12,
  },
  {
    label: "User ID",
    name: "id",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Status",
    name: "status",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Account Created",
    name: "createdAt",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Last Updated",
    name: "updatedAt",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Subscription Information",
    type: "label",
    span: 12,
  },
  {
    label: "Subscription Tier",
    name: "subscriptionTier",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Subscription Status",
    name: "subscriptionStatus",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Trial End Date",
    name: "trialEndDate",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Next Billing Date",
    name: "nextBillingDate",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Enabled Features",
    type: "label",
    span: 12,
  },
  {
    label: "SACCO Features",
    name: "saccoFeaturesEnabled",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Staff Management",
    name: "staffManagementEnabled",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Payroll",
    name: "payrollEnabled",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Collections Module",
    name: "collectionsModuleEnabled",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Custom Workflows",
    name: "customWorkflowsEnabled",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Advanced Reporting",
    name: "advancedReportingEnabled",
    type: "text",
    span: 6,
    disabled: true,
  },
  {
    label: "Limits & Configuration",
    type: "label",
    span: 12,
  },
  {
    label: "Max Users",
    name: "maxUsers",
    type: "text",
    span: 4,
    disabled: true,
  },
  {
    label: "Max Branches",
    name: "maxBranches",
    type: "text",
    span: 4,
    disabled: true,
  },
  {
    label: "Max Staff Per Branch",
    name: "maxStaffPerBranch",
    type: "text",
    span: 4,
    disabled: true,
  },
];
