const loanCalculatorForm = [
  // Principal Settings
  
  
  {
    label: "Principal Amount",
    name: "principalAmount",
    type: "number",
    required: true,
    span: 12,
    helperText: "The amount of money being lent.",
  },

  // Interest Settings
  {
    label: "Interest Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Interest Method",
    name: "interestMethod",
    type: "select",
    span: 12,
    required: true,
    defaultValue: "reducing_balance_equal_installments",
    options: [
      { value: "compound_interest_accrued", label: "Compound Interest - Accrued" },
      { value: "compound_interest_equal_installments", label: "Compound Interest - Equal Installments" },
      { value: "flat", label: "Flat" },
      { value: "interest_only", label: "Interest-Only" },
      { value: "reducing_balance_equal_installments", label: "Reducing Balance - Equal Installments" },
      { value: "reducing_balance_equal_principal", label: "Reducing Balance - Equal Principal" },
    ],
  },
  {
    label: "Interest Type",
    name: "interestType",
    type: "radio",
    span: 6,
    required: true,
    defaultValue: "percentage",
    options: [
      { value: "percentage", label: "Percentage" },
      { value: "fixed", label: "Fixed Amount" },
    ],
  },
  {
    type: "textAndDropdown",
    span: 6,
    textLabel: "Interest Rate",
    textName: "interestRate",
    textType: "number",
    textRequired: true,
    textDefaultValue: "",
    textPlaceholder: "",
    dynamicLabelMap: {
      percentage: "Interest Rate",
      fixed: "Interest Amount",
    },
    dependsOn: "interestType",
    dropdownLabel: "",
    dropdownName: "interestPeriod",
    dropdownRequired: true,
    dropdownDefaultValue: "per_month",
    dropdownOptions: [
      { value: "per_day", label: "Per Day" },
      { value: "per_week", label: "Per Week" },
      { value: "per_month", label: "Per Month" },
      { value: "per_year", label: "Per Year" },
      { value: "per_loan", label: "Per Loan" },
    ],
  },

  // Duration Settings
  {
    label: "Duration Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Loan Start Date",
    name: "loanStartDate",
    type: "date",
    required: true,
    span: 6,
  },
  {
    type: "textAndDropdown",
    span: 6,
    textLabel: "Loan Duration",
    textName: "loanDuration",
    textType: "number",
    textRequired: true,
    textDefaultValue: "",
    textPlaceholder: "",
    textInputProps: {
      min: 1,
    },
    dropdownLabel: "",
    dropdownName: "durationPeriod",
    dropdownRequired: true,
    dropdownDefaultValue: "months",
    dropdownOptions: [
      { value: "days", label: "Days" },
      { value: "weeks", label: "Weeks" },
      { value: "months", label: "Months" },
      { value: "years", label: "Years" },
    ],
  },

  // Repayment Settings
  {
    label: "Repayment Settings",
    type: "label",
    span: 12,
  },
  {
    label: "Repayment Frequency",
    name: "repaymentFrequencyType",
    type: "radio",
    required: true,
    span: 12,
    defaultValue: "interval",
    options: [
      { value: "interval", label: "Interval Based" },
      { value: "lumpSum", label: "Lump Sum" },
      { value: "setDays", label: "Set Days of the Week" },
      { value: "setDates", label: "Set Dates of the Month" },
    ],
    helperText: "Choose how repayments will be scheduled.",
  },
  {
    label: "Repayment Interval",
    name: "repaymentFrequency",
    type: "select",
    span: 6,
    defaultValue: "monthly",
    options: [
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
      { value: "biweekly", label: "Every 2 weeks" },
      { value: "monthly", label: "Monthly" },
      { value: "quarterly", label: "Quarterly" },
      { value: "every_4_months", label: "Every 4 months" },
      { value: "semi_annual", label: "Semi-annual" },
      { value: "every_9_months", label: "Every 9 months" },
      { value: "yearly", label: "Yearly" },
    ],
    helperText: "Select the interval for repayment.",
    dependsOn: "repaymentFrequencyType",
    dependsOnValue: "interval",
  },
  {
    label: "Payment Days",
    name: "customPaymentDays",
    type: "selectMultiple",
    span: 6,
    defaultValue: [],
    options: [
      { value: "Monday", label: "Monday" },
      { value: "Tuesday", label: "Tuesday" },
      { value: "Wednesday", label: "Wednesday" },
      { value: "Thursday", label: "Thursday" },
      { value: "Friday", label: "Friday" },
      { value: "Saturday", label: "Saturday" },
      { value: "Sunday", label: "Sunday" },
    ],
    helperText: "Select the days of the week on which payments should be received.",
    dependsOn: "repaymentFrequencyType",
    dependsOnValue: "setDays",
    showSelectAll: false,
  },
  {
    label: "Payment Dates",
    name: "customPaymentDates",
    type: "selectMultiple",
    span: 6,
    defaultValue: [],
    options: [
      { value: "1", label: "1st" },
      { value: "2", label: "2nd" },
      { value: "3", label: "3rd" },
      { value: "4", label: "4th" },
      { value: "5", label: "5th" },
      { value: "6", label: "6th" },
      { value: "7", label: "7th" },
      { value: "8", label: "8th" },
      { value: "9", label: "9th" },
      { value: "10", label: "10th" },
      { value: "11", label: "11th" },
      { value: "12", label: "12th" },
      { value: "13", label: "13th" },
      { value: "14", label: "14th" },
      { value: "15", label: "15th" },
      { value: "16", label: "16th" },
      { value: "17", label: "17th" },
      { value: "18", label: "18th" },
      { value: "19", label: "19th" },
      { value: "20", label: "20th" },
      { value: "21", label: "21st" },
      { value: "22", label: "22nd" },
      { value: "23", label: "23rd" },
      { value: "24", label: "24th" },
      { value: "25", label: "25th" },
      { value: "26", label: "26th" },
      { value: "27", label: "27th" },
      { value: "28", label: "28th" },
      { value: "29", label: "29th" },
      { value: "30", label: "30th" },
      { value: "31", label: "31st" },
    ],
    helperText: "Select the dates of the month on which payments should be received.",
    dependsOn: "repaymentFrequencyType",
    dependsOnValue: "setDates",
    showSelectAll: false,
  },
];

export default loanCalculatorForm;
