const editLoanProductForm = [
  {
    label: "Loan Product Name*",
    name: "name",
    type: "text",
    required: true,
    span: 12,
    validationType: "string",
    validationMessage: "Loan Product Name is required",
    maxLength: 100,
  },
  {
    label: "Branches",
    name: "branch",
    type: "select",
    span: 12,
    multiple: true,
    options: [], // Will be populated dynamically
    dynamicoptions: "true",
  },
  // Principal Settings
  {
    label: "Minimum Principal",
    name: "minPrincipal",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  {
    label: "Default Principal",
    name: "defaultPrincipal",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  {
    label: "Maximum Principal",
    name: "maxPrincipal",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  // Interest Settings
  {
    label: "Interest Method",
    name: "interestMethod",
    type: "select",
    span: 4,
    options: [
      { value: "flat", label: "Flat" },
      { value: "declining_balance", label: "Declining Balance" },
    ],
  },
  {
    label: "Interest Type",
    name: "interestType",
    type: "select",
    span: 4,
    options: [
      { value: "percentage", label: "Percentage" },
      { value: "fixed", label: "Fixed Amount" },
    ],
  },
  {
    label: "Interest Period",
    name: "interestPeriod",
    type: "select",
    span: 4,
    options: [
        { value: "per_day", label: "Per Day" },
        { value: "per_week", label: "Per Week" },
        { value: "per_month", label: "Per Month" },
        { value: "per_year", label: "Per Year" },
        { value: "per_loan_cycle", label: "Per Loan Cycle" },
    ],
  },
  {
    label: "Minimum Interest",
    name: "minInterest",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  {
    label: "Default Interest",
    name: "defaultInterest",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  {
    label: "Maximum Interest",
    name: "maxInterest",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  // Duration Settings
  {
    label: "Duration Period",
    name: "durationPeriod",
    type: "select",
    span: 12,
    options: [
      { value: "days", label: "Days" },
      { value: "weeks", label: "Weeks" },
      { value: "months", label: "Months" },
      { value: "years", label: "Years" },
    ],
  },
  {
    label: "Minimum Duration",
    name: "minDuration",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  {
    label: "Default Duration",
    name: "defaultDuration",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  {
    label: "Maximum Duration",
    name: "maxDuration",
    type: "number",
    span: 4,
    validationType: "number",
    min: 0,
  },
  // Repayment Settings
  {
    label: "Repayment Frequency",
    name: "repaymentFrequency",
    type: "select",
    span: 12,
    options: [
      { value: "daily", label: "Daily" },
      { value: "weekly", label: "Weekly" },
      { value: "biweekly", label: "Bi-weekly" },
      { value: "monthly", label: "Monthly" },
      { value: "bimonthly", label: "Bimonthly" },
      { value: "quarterly", label: "Quarterly" },
      { value: "every_4_months", label: "Every 4 months" },
      { value: "semi_annual", label: "Semi-annual" },
      { value: "every_9_months", label: "Every 9 months" },
      { value: "yearly", label: "Yearly" },
      { value: "lump_sum", label: "Lump Sum" },
    ],
  },
  // Loan Maturity Settings
  {
    label: "Extend Loan After Maturity",
    name: "extendLoanAfterMaturity",
    type: "select",
    span: 6,
    options: [
      { value: "true", label: "Yes" },
      { value: "false", label: "No" },
    ],
  },
  {
    label: "Interest Type After Maturity",
    name: "interestTypeMaturity",
    type: "select",
    span: 6,
    options: [
      { value: "fixed", label: "Fixed" },
      { value: "percentage", label: "Percentage" },
    ],
  },
  {
    label: "Calculate Interest On",
    name: "calculateInterestOn",
    type: "select",
    span: 6,
    options: [
      { value: "principal_only", label: "Principal Only" },
      { value: "principal_and_interest", label: "Principal and Interest" },
    ],
  },
  {
    label: "Loan Interest Rate After Maturity",
    name: "loanInterestRateAfterMaturity",
    type: "number",
    span: 6,
    validationType: "number",
    min: 0,
  },
  {
    label: "Recurring Period After Maturity Unit",
    name: "recurringPeriodAfterMaturityUnit",
    type: "select",
    span: 6,
    options: [
      { value: "days", label: "Days" },
      { value: "weeks", label: "Weeks" },
      { value: "months", label: "Months" },
      { value: "years", label: "Years" },
    ],
  },
  {
    label: "Loan Fees",
    name: "loanFees",
    type: "select",
    span: 12,
    multiple: true,
    options: [], // Will be populated dynamically
    dynamicoptions: "true",
  },
];

export default editLoanProductForm;
