const createAccountForm = [
  {
    label: "Account Name",
    name: "name",
    type: "text",
    required: true,
    span: 6,
    placeholder: "Account Name",
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Name contains invalid characters",
    maxLength: 100,
  },
  {
    label: "Opening Balance",
    name: "openingBalance",
    type: "number",
    required: false,
    span: 6,
    validationType: "number",
    min: 0,
    defaultValue: 0,
  },
  {
    label: "Currency",
    name: "currency",
    type: "select",
    required: true,
    span: 6,
    placeholder: "Select Currency",
    validationType: "string",
    helperText: "Currency cannot be changed after account creation",
  },
  {
    label: "Description",
    name: "description",
    type: "textarea",
    required: false,
    span: 6,
    placeholder: "Description (optional)",
    rows: 1,
    validationType: "string",
    validationPattern: /^[^,"'!{}]+$/,
    validationMessage: "Description contains invalid characters",
    maxLength: 200,
  },
  {
    label: "Status",
    name: "status",
    type: "radio",
    required: false,
    span: 6,
    options: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
    ],
    showOnlyInEditMode: true,
  },
];

export default createAccountForm;